config/routes.rb
Rails.application.routes.draw do
  get 'test/index'

  get 'reports' => 'policereport#show', as: :reports
  get 'reports/new' => 'policereport#new', as: :new_report
  post 'reports/create' => 'policereport#create', as: :create_report

  root 'test#index'

end

app/models/policereport.rb
class Policereport < ActiveRecord::Base
	validates :description, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :phonenumber, presence: true
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/policereport_controller.rb
class PolicereportController < ApplicationController
	def show
		@reports = Policereport.all
		sleep(2.0);
  	render json: @reports
	end

	def new
		@policereport = Policereport.new
	end

	def create
		report = Policereport.new(report_params)
		
		if report.save
			redirect_to '/'
		else
			render 'new'
		end
	end

	private
		def report_params
			puts params
		  params.require(:policereport).permit(:description, :city, :state, :phonenumber, :name)
		end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  	@reports = Policereport.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/policereport_helper.rb
module PolicereportHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxRequests</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/policereport/new.html.erb
<h1>Add a new Report</h1>
<%= form_for @policereport, :url => create_report_path do |form| %>

  <div>
    <%= form.label :description, "Description:" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :name, "Name:" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :city, "City:" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, "State:" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :phonenumber, "Phone Number:" %>
    <%= form.text_field :phonenumber %>
  </div>

  <div class='buttons'>
    <%= form.submit "Save" %>
  </div>

<% end %>